# Generated by Django 3.2.6 on 2021-08-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_date_added2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_added2',
        ),
    ]
